# Generated by Django 5.2.8 on 2025-11-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número telefónico del cliente (opcional)', max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
