# Generated by Django 5.2.8 on 2025-11-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz_crud', '0002_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección física del cliente (opcional)', max_length=255, null=True, verbose_name='Dirección'),
        ),
    ]
