# Generated by Django 5.2.6 on 2025-11-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz_crud', '0003_cliente_direccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cotizacion',
        ),
    ]
