# Generated by Django 4.2 on 2025-11-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz_crud', '0004_delete_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Notas o descripción adicional del cliente (opcional)', null=True, verbose_name='Descripción'),
        ),
    ]
