# Generated by Django 5.2.8 on 2025-11-08 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del cliente', max_length=255)),
                ('correo', models.EmailField(help_text='Correo electrónico del cliente (debe ser único)', max_length=254, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el cliente', verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='client',
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó la cotización', verbose_name='Fecha de creación')),
                ('total', models.DecimalField(decimal_places=2, help_text='Monto total de la cotización', max_digits=12, verbose_name='Total en pesos')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales de la cotización', null=True, verbose_name='Descripción')),
                ('cliente', models.ForeignKey(help_text='Cliente al que pertenece esta cotización', on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='quotations.cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
