# Generated by Django 5.2.8 on 2025-11-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_cliente_remove_quotation_client_cotizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Cotizacion',
        ),
    ]
