# Generated by Django 5.2.6 on 2025-11-19 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz_crud', '0004_delete_cotizacion'),
        ('quotations', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otrosmateriales',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='quotationrequest',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='quotationresult',
            name='solicitud',
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho_cm', models.FloatField(help_text='Ancho de la marquilla en centímetros', verbose_name='Ancho (cm)')),
                ('alto_cm', models.FloatField(help_text='Alto de la marquilla en centímetros', verbose_name='Alto (cm)')),
                ('espacio_entre_cm', models.FloatField(default=0.5, help_text='Espacio entre marquillas en el molde', verbose_name='Espacio entre marquillas (cm)')),
                ('cantidad_horizontal', models.IntegerField(help_text='Cantidad de marquillas en horizontal por molde', verbose_name='Marquillas horizontales')),
                ('cantidad_vertical', models.IntegerField(help_text='Cantidad de marquillas en vertical por molde', verbose_name='Marquillas verticales')),
                ('cantidad', models.IntegerField(help_text='Cantidad total de marquillas a producir', verbose_name='Cantidad total a producir')),
                ('valor_por_troquelada', models.FloatField(help_text='Costo de la troquelada', verbose_name='Valor por troquelada')),
                ('montaje', models.FloatField(default=0, help_text='Costo del montaje', verbose_name='Valor del montaje')),
                ('medida', models.FloatField(default=0, help_text='Costo de la medida', verbose_name='Valor de la medida')),
                ('espesor', models.CharField(choices=[('2_mm', '2mm'), ('3_mm', '3mm'), ('1_mm', '1mm'), ('1.2_mm', '1.2mm'), ('1.5_mm', '1.5mm'), ('5_mm', '5mm')], default='2_mm', help_text='Espesor del material', max_length=10, verbose_name='Espesor')),
                ('bolsa_individual', models.FloatField(default=0, help_text='Costo de bolsa individual', verbose_name='Bolsa individual')),
                ('sellada', models.FloatField(default=0, help_text='Costo de sellado', verbose_name='Sellada')),
                ('cortada', models.FloatField(default=0, help_text='Costo de corte', verbose_name='Cortada')),
                ('empaque_final', models.FloatField(default=0, help_text='Costo de empaque final', verbose_name='Empaque final')),
                ('llenada_gel', models.FloatField(default=0, help_text='Costo de llenado de gel', verbose_name='Llenada gel')),
                ('pin_soporte', models.FloatField(default=0, help_text='Costo de pin soporte', verbose_name='Pin soporte')),
                ('samblasted', models.FloatField(default=0, help_text='Costo de proceso samblasted', verbose_name='Samblasted')),
                ('mo_rubber', models.FloatField(default=0, help_text='Costo de mano de obra en rubber', verbose_name='MO Rubber')),
                ('numero_plotter', models.FloatField(default=0, help_text='Costo de número plotter', verbose_name='Número Plotter')),
                ('perforada', models.FloatField(default=0, help_text='Costo de perforado', verbose_name='Perforada')),
                ('guillotina', models.FloatField(default=0, help_text='Costo de guillotina', verbose_name='Guillotina')),
                ('largo_total_cm', models.FloatField(blank=True, help_text='Largo total del molde incluyendo márgenes', null=True, verbose_name='Largo total del molde (cm)')),
                ('alto_total_cm', models.FloatField(blank=True, help_text='Alto total del molde incluyendo márgenes', null=True, verbose_name='Alto total del molde (cm)')),
                ('area_total_cm2', models.FloatField(blank=True, help_text='Área total del molde en centímetros cuadrados', null=True, verbose_name='Área total (cm²)')),
                ('gramos_total', models.FloatField(blank=True, help_text='Gramos totales de material del molde', null=True, verbose_name='Gramos totales')),
                ('gramos_por_cm2', models.FloatField(blank=True, help_text='Gramos de material por centímetro cuadrado', null=True, verbose_name='Gramos por cm²')),
                ('costo_por_gramo', models.FloatField(blank=True, help_text='Costo unitario por gramo de material', null=True, verbose_name='Costo por gramo')),
                ('material', models.FloatField(blank=True, help_text='Costo de material por marquilla', null=True, verbose_name='Costo de material (por unidad)')),
                ('total_material', models.FloatField(blank=True, help_text='Total de material (material + montaje + medida)', null=True, verbose_name='Total material')),
                ('total_armado', models.FloatField(blank=True, help_text='Total de costos de armado/empaquetado', null=True, verbose_name='Total armado')),
                ('otros_materiales_total', models.FloatField(blank=True, help_text='Total de otros materiales y procesos', null=True, verbose_name='Total otros materiales')),
                ('cif_8', models.FloatField(blank=True, help_text='CIF calculado al 8%', null=True, verbose_name='CIF 8%')),
                ('cif_10', models.FloatField(blank=True, help_text='CIF calculado al 10%', null=True, verbose_name='CIF 10%')),
                ('cif_15', models.FloatField(blank=True, help_text='CIF calculado al 15%', null=True, verbose_name='CIF 15%')),
                ('admon', models.FloatField(blank=True, help_text='Costos de administración', null=True, verbose_name='Administración')),
                ('costo_total', models.FloatField(blank=True, help_text='Costo total de producir la marquilla', null=True, verbose_name='Costo total de producción')),
                ('precio_utilidad_45', models.FloatField(blank=True, help_text='Precio de venta con 45% de utilidad', null=True, verbose_name='Precio con utilidad 45%')),
                ('precio_utilidad_28', models.FloatField(blank=True, help_text='Precio de venta con 28% de utilidad', null=True, verbose_name='Precio con utilidad 28%')),
                ('precio_utilidad_17', models.FloatField(blank=True, help_text='Precio de venta con 17% de utilidad', null=True, verbose_name='Precio con utilidad 17%')),
                ('precio_utilidad_11', models.FloatField(blank=True, help_text='Precio de venta con 11% de utilidad', null=True, verbose_name='Precio con utilidad 11%')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó la cotización', verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de modificación')),
                ('cliente', models.ForeignKey(help_text='Cliente que solicita la cotización', on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='interfaz_crud.cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'quotations_quotation',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='CostosArmado',
        ),
        migrations.DeleteModel(
            name='OtrosMateriales',
        ),
        migrations.DeleteModel(
            name='QuotationRequest',
        ),
        migrations.DeleteModel(
            name='QuotationResult',
        ),
    ]
