# Generated by Django 5.2.6 on 2025-11-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_remove_otrosmateriales_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quotation',
            table='quotation',
        ),
    ]
