# Generated by Django 5.2.6 on 2025-11-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_alter_quotation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada')], default='pendiente', help_text='Estado de la cotización', max_length=20, verbose_name='Estado'),
        ),
    ]
