# Generated by Django 5.2.6 on 2025-11-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_quotation_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada')], default='pendiente', help_text='Estado de la cotización', max_length=20, verbose_name='Estado'),
        ),
    ]
